models:
  - make: Tesla
    model: Model Y
    finn_query: "tesla model y"
  - make: Tesla
    model: Model 3
    finn_query: "tesla model 3"
  - make: Volkswagen
    model: ID.4
    finn_query: "volkswagen id.4"
  - make: Nissan
    model: Leaf
    finn_query: "nissan leaf"
  - make: BMW
    model: i3
    finn_query: "bmw i3"
  - make: Audi
    model: e-tron
    finn_query: "audi e-tron"
  - make: Toyota
    model: RAV4
    finn_query: "toyota rav4"
  - make: Hyundai
    model: IONIQ 5
    finn_query: "hyundai ioniq 5"
  - make: Skoda
    model: Enyaq
    finn_query: "skoda enyaq"
